### ISSUE TITLE
test all file formats on latest Blender

### ISSUE THREAD

**Issue by mrwonko** [mrwonko/Blender-Jedi-Academy-Tools#22]
I only know that glm/gla works properly in new Blender versions. I had a report of ASE import being broken, and need to see what else is, too.

**Comment by savenar** [comment]
Greetings
Version Blender 3.4 When trying to import a glm model, I got the following error. Do not tell me how to solve the problem?
Python: Traceback (most recent call last):
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2Operators.py", line 92, in execute
    success, message = scene.saveToBlender(scale, skin, self.guessTextures, self.skeletonFixes)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2Scene.py", line 141, in saveToBlender
    success, message = self.glm.saveToBlender(self.basepath, self.gla, scene_root, skin_rel, guessTextures)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2GLM.py", line 1051, in saveToBlender
    self.LODCollection.saveToBlender(data)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2GLM.py", line 875, in saveToBlender
    LOD.saveToBlender(data, root)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2GLM.py", line 806, in saveToBlender
    obj = surface.saveToBlender(data, self.level)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAG2GLM.py", line 648, in saveToBlender
    material = data.materialManager.getMaterial(name, surfaceData.shader)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\jediacademy\JAMaterialmanager.py", line 88, in getMaterial
    bsdf = mat.node_tree.nodes["Principled BSDF"]
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**Comment by sqwirral** [comment]
No problems were noticed importing ASE files with Blender 3.6.1. Thank you for the script!

**Comment by SomaZ** [comment]
Tested everything and fixed up what was broken in 
https://github.com/mrwonko/Blender-Jedi-Academy-Tools/pull/70
